#!/bin/bash
touch ~/.bashrc; cp ~/.bashrc ~/.bashrc.backup; b=~/.bashrc

exar=('export http_proxy=' 'export https_proxy=' 'export ftp_proxy=')

rm_proxy () {
    echo Removing Proxy Settings from .bashrc
    for x in "${exar[@]}"; do
      sed -i "/$x/d" $b
    done
}

mk_nullproxy () {
  for i in "${exar[@]}"; do
    echo "$i''" >> $b
  done
}

f5 () {
  echo Refeshing Terminal...
  bash
}

echo 1. Set Proxy 2. Remove Proxy
read pChoice

if [ $pChoice -eq 1 ]; then
    rm_proxy
    echo Enter Username \(john.smith1\); read pUsername
    echo Enter Password;                 read -s pPassword; echo ' '

    fullproxy="http://$pUsername:$pPassword@proxy.det.nsw.edu.au:8080/"
    for i in "${exar[@]}"; do
      echo "$i$fullproxy" >> $b
    done
    f5

elif [ $pChoice -eq 2 ]; then
    rm_proxy; mk_nullproxy; f5
fi
